In [39]:
#!pip install nbconvert

In [1]:
# libraries
import pandas as pd
import numpy as np
import functools as ft
import seaborn as sns
import matplotlib.pyplot as plt
# modelacion
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.svm import LinearSVC, SVC
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
import lightgbm as lgb
# encoding
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder, StandardScaler, MinMaxScaler

# seleccion de modelos
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform, randint

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report, roc_curve, auc,
    roc_auc_score
)
from sklearn.feature_selection import (
    SelectKBest, f_classif, chi2, mutual_info_classif,
    RFE, SelectFromModel, VarianceThreshold
)

#otros
import time
import warnings
import nbconvert
warnings.filterwarnings('ignore')

## carga de datos

In [2]:
dt_merge = pd.read_csv("/home/estebanm/Escritorio/docs_tfm/Datos_desde_audios_varias_fuentes/merge_variables/audio_features.csv")
dt_merge.head()

,name,duracion_s,rms_mean,rms_std,sujeto,dementia,dementia type,gender,ethnicity,datasplit,...,syntax_depth,std_words_per_sent,mean_word_length,std_word_length,function_ratio,transcript,duration,pause_prob,language,wpm
0,Abe Burrows,71.019688,0.071390,0.050389,abeburrows,1,Alzheimer,male,Caucasian/White,train,...,7.666667,75.330383,3.789030,2.132184,0.611814,to me Bob was he was worried when I became a p...,72.76,0.263634,en,195.437053
1,Aileen Hernandez,47.000000,0.144582,0.090372,aileenhernandez,1,Dementia,female,Black/African American,train,...,5.500000,13.379088,3.810811,1.850315,0.628378,This is not going to sound like very ladylike....,47.04,0.122493,en,188.775510
2,Aileen Hernandez,38.000000,0.123960,0.079574,aileenhernandez,1,Dementia,female,Black/African American,train,...,5.428571,12.290697,3.625000,1.952562,0.585938,I arrive at my first political science class. ...,38.40,0.000328,en,200.000000
3,Aileen Hernandez,90.000000,0.061281,0.049997,aileenhernandez,1,Dementia,female,Black/African American,train,...,5.357143,9.598044,4.003597,2.092292,0.575540,We are more conscious in this state now about ...,89.00,0.002673,en,187.415730
4,Alan Ramsey,55.000000,0.060310,0.051383,alanramsey,1,Dementia,male,Caucasian/White,train,...,4.500000,8.890444,4.286585,2.216252,0.640244,"I'm pretty jaundiced one, Virginia, I have to ...",55.00,0.149834,en,178.909091

In [3]:
# sacar variables que no son parte del analisis
dt_merge.drop(['language', 'transcript', 'audio_file', 'datasplit', 'sujeto', 'name'], axis=1, inplace=True)

In [4]:
df = dt_merge.copy()

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 353 entries, 0 to 352
Data columns (total 74 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   duracion_s                                  353 non-null    float64
 1   rms_mean                                    353 non-null    float64
 2   rms_std                                     353 non-null    float64
 3   dementia                                    353 non-null    int64
 4   dementia type                               218 non-null    object
 5   gender                                      216 non-null    object
 6   ethnicity                                   216 non-null    object
 7   f0_mean                                     353 non-null    float64
 8   f0_std                                      353 non-null    float64
 9   f0_range                                    353 non-null    float64
 10  articulation_rate                           353 non-null    float64
 11  silence_segments_n                          353 non-null    float64
 12  silence_dur_mean_s                          353 non-null    float64
 13  silence_ratio_rms                           353 non-null    float64
 14  silence_dur_std_s                           353 non-null    float64
 15  silence_dur_max_s                           353 non-null    float64
 16  speech_rate                                 353 non-null    float64
 17  voiced_dur_mean_s                           353 non-null    float64
 18  voiced_segments_n                           353 non-null    float64
 19  voiced_ratio                                353 non-null    float64
 20  voiced_dur_cv                               353 non-null    float64
 21  F0semitoneFrom27.5Hz_sma3nz_amean           353 non-null    float64
 22  F0semitoneFrom27.5Hz_sma3nz_stddevNorm      353 non-null    float64
 23  F0semitoneFrom27.5Hz_sma3nz_percentile20.0  353 non-null    float64
 24  F0semitoneFrom27.5Hz_sma3nz_percentile50.0  353 non-null    float64
 25  F0semitoneFrom27.5Hz_sma3nz_percentile80.0  353 non-null    float64
 26  F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2    353 non-null    float64
 27  loudness_sma3_amean                         353 non-null    float64
 28  loudness_sma3_stddevNorm                    353 non-null    float64
 29  jitterLocal_sma3nz_amean                    353 non-null    float64
 30  shimmerLocaldB_sma3nz_amean                 353 non-null    float64
 31  HNRdBACF_sma3nz_amean                       353 non-null    float64
 32  alphaRatioV_sma3nz_amean                    353 non-null    float64
 33  hammarbergIndexV_sma3nz_amean               353 non-null    float64
 34  slopeV0-500_sma3nz_amean                    353 non-null    float64
 35  slopeV500-1500_sma3nz_amean                 353 non-null    float64
 36  VoicedSegmentsPerSec                        353 non-null    float64
 37  MeanVoicedSegmentLengthSec                  353 non-null    float64
 38  StddevVoicedSegmentLengthSec                353 non-null    float64
 39  MeanUnvoicedSegmentLength                   353 non-null    float64
 40  StddevUnvoicedSegmentLength                 353 non-null    float64
 41  voiced_seg_cv                               353 non-null    float64
 42  unvoiced_seg_cv                             353 non-null    float64
 43  n_chars                                     353 non-null    int64
 44  n_tokens                                    353 non-null    int64
 45  n_words                                     353 non-null    int64
 46  n_sents                                     353 non-null    int64
 47  n_nouns                                     353 non-null    int64
 48  n_verbs                                     353 non-null    int64
 49  n_adjs                                      353 non-null    int64
 50  n_advs                                      353 non-null    int64
 51  n_prons                                     353 non-null    int64
 52  n_propns                                    353 non-null    int64
 53  n_content_words                             353 non-null    int64
 54  n_function_words                            353 non-null    int64
 55  mean_words_per_sent                         352 non-null    float64
 56  ttr                                         352 non-null    float64
 57  mattr_50                                    352 non-null    float64
 58  content_ratio                               352 non-null    float64
 59  noun_ratio                                  352 non-null    float64
 60  verb_ratio                                  352 non-null    float64
 61  adj_ratio                                   352 non-null    float64
 62  adv_ratio                                   352 non-null    float64
 63  pron_ratio                                  352 non-null    float64
 64  propn_ratio                                 352 non-null    float64
 65  noun_pron_ratio                             352 non-null    float64
 66  syntax_depth                                352 non-null    float64
 67  std_words_per_sent                          335 non-null    float64
 68  mean_word_length                            352 non-null    float64
 69  std_word_length                             352 non-null    float64
 70  function_ratio                              352 non-null    float64
 71  duration                                    353 non-null    float64
 72  pause_prob                                  353 non-null    float64
 73  wpm                                         353 non-null    float64
dtypes: float64(58), int64(13), object(3)
memory usage: 204.2+ KB

# Generacion de datos

## Clustering

In [6]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import NearestNeighbors
from sklearn.impute import SimpleImputer

In [7]:
class MedicalDataAugmentor:
    def __init__(self, n_neighbors=3, random_state=42):
        self.n_neighbors = n_neighbors
        self.random_state = random_state
        np.random.seed(random_state)
        self.scaler = StandardScaler()
        self.imputer = SimpleImputer(strategy='median')

    def augment_mixed_data(self, df, target_size=2000):
        """
        Aumento de datos para mixed data -- continuas + categoricas
        """

        # 1. separar variable
        target_col = 'dementia'
        cat_cols = ['dementia type', 'gender', 'ethnicity']

        # 2. codificar categoricas
        df_processed = df.copy()

        # 2.1 manejar los nat en categoricas
        for col in cat_cols:
            df_processed[col] = df_processed[col].fillna('Unknown')

        # 2.2 manejar nan en continuas
        numeric_cols = df_processed.select_dtypes(include=[np.number]).columns.tolist()
        # excluir la columna objetivo si esta presente
        numeric_cols = [col for col in numeric_cols if col != target_col]

        # imputar valores faltantes en columnas numericas
        df_processed[numeric_cols] = self.imputer.fit_transform(df_processed[numeric_cols])

        # 3. codificar categoricas
        df_encoded = df_processed.copy()
        
        label_encoders = {}

        for col in cat_cols:
            le = LabelEncoder()
            df_encoded[col] = le.fit_transform(df_processed[col])
            label_encoders[col] = le

        # 4. normalizar todas las variables
        scaler = StandardScaler()
        cols_to_scale = [c for c in df_encoded.columns if c not in [target_col]]
        df_scaled = scaler.fit_transform(df_encoded[cols_to_scale])

        # 5. encontrar vecinos mas cercanos
        nn = NearestNeighbors(n_neighbors=self.n_neighbors)
        nn.fit(df_scaled)

        # 6. Generar nuevas muestras
        synthetic_samples = []

        while len(synthetic_samples) < target_size:
            # seleccionar punto aleatorio
            idx = np.random.randint(0, len(df_scaled))
            point = df_scaled[idx].reshape(1, -1)

            # encontrar vecinos
            distances, indices = nn.kneighbors(point)

            # seleccionar vecio aleatorio
            neighbor_idx = np.random.choice(indices[0][1:])

            # interpolar
            alpha = np.random.random()
            new_point = point + alpha * (df_scaled[neighbor_idx] - point[0])

            # anadir ruido gaussiano pequeno
            noise = np.random.normal(0, 0.01, size=new_point.shape)
            new_point += noise

            synthetic_samples.append(new_point[0])

        # 7. revertir transformaciones
        synthetic_array = np.array(synthetic_samples[:target_size])
        synthetic_scaled = scaler.inverse_transform(synthetic_array)

        # 8. crear dataframe
        synthetic_df = pd.DataFrame(synthetic_scaled, columns= cols_to_scale)

        # 9. proces variables categoricas

        for col in cat_cols:
            #redondear valores codificados
            synthetic_df[col] = synthetic_df[col].round().astype(int)
            # clip a rangos validos
            synthetic_df[col] = synthetic_df[col].clip(0, len(label_encoders[col].classes_)-1)
            # decodificador
            synthetic_df[col] = label_encoders[col].inverse_transform(synthetic_df[col].astype(int))

        # 10. agregar variable objetivo -- basado en vecinos
        synthetic_df[target_col] = self._assign_target_values(df, synthetic_df, cat_cols)

        return synthetic_df


    def _assign_target_values(self, original_df, synthetic_df, cat_cols):
        """ 
        Asignar valores de target basados en similitud
        """
        target_values = []

        for i, synth_row in synthetic_df.iterrows():
             # calcular similitud con puntos originales
            similarities = []

            for i, orig_row in original_df.iterrows():
                sim = 0
                # similitud en variables categoricas
                for cat_col in cat_cols:
                    if synth_row[cat_col] == orig_row[cat_col]:
                        sim += 1

                # similitud en variables continuas -- simplificado
                cont_cols = [c for c in synthetic_df.columns if c not in cat_cols + ['dementia']]

                for cont_col in cont_cols[:5]:
                    sim += 1 / (1 + abs(synth_row[cont_col] - orig_row[cont_col]))
                        
                similarities.append((sim, orig_row['dementia']))
                    
            # tomar el target del mas similar
            similarities.sort(reverse=True)
            target_values.append(similarities[0][1])

        return target_values

In [8]:
# aplicacion
augmentor = MedicalDataAugmentor(n_neighbors=3)
synthetic_data = augmentor.augment_mixed_data(df, target_size=5000)
synthetic_data.head()

,duracion_s,rms_mean,rms_std,dementia type,gender,ethnicity,f0_mean,f0_std,f0_range,articulation_rate,...,noun_pron_ratio,syntax_depth,std_words_per_sent,mean_word_length,std_word_length,function_ratio,duration,pause_prob,wpm,dementia
0,89.988196,0.036822,0.041091,Alzheimer,male,Caucasian/White,114.168930,16.642410,119.825270,1.198481,...,-1.332362e+09,3.635765,7.754072,4.067011,2.223519,0.607368,89.629681,0.013319,118.579132,1
1,29.925191,0.137287,0.088627,Dementia,female,Caucasian/White,253.413488,93.671352,456.639384,1.671122,...,-2.277397e+10,3.379363,15.586891,3.685589,2.023116,0.545056,28.267641,0.499583,158.165276,1
2,29.983313,0.135232,0.086324,Dementia,female,Caucasian/White,253.728516,88.644382,426.515383,1.653689,...,-5.833245e+09,3.511172,14.075525,3.749044,2.101150,0.542580,28.926076,0.484848,159.101324,1
3,55.943104,0.138229,0.075856,Unknown,Unknown,Unknown,184.745227,52.625316,381.154553,1.998105,...,1.088529e+10,3.195723,11.222020,4.054252,2.038020,0.627019,56.658212,0.742196,165.269704,1
4,89.971841,0.036050,0.040708,Alzheimer,male,Caucasian/White,113.763308,16.533740,121.187389,1.194309,...,-2.043078e+10,3.621857,7.642944,4.061336,2.221780,0.605613,90.068489,0.009043,119.054960,1

In [9]:
synthetic_data.shape

(5000, 74)

In [10]:
synthetic_data.dementia.value_counts()

dementia
0    2589
1    2411
Name: count, dtype: int64

In [34]:
# validaciones
def validate_augmented_data(original, synthetic):
    """Validaciones básicas para datos médicos """

    print("validación de datos médicos")

    #1. estadísticas descriptivas básicas
    print("Estadisticas por variable")
    for col in original.select_dtypes(include=[np.number]).columns[:10]:
        orig_mean = original[col].mean()
        synth_mean = synthetic[col].mean()
        diff_pct = abs(orig_mean - synth_mean)/ orig_mean * 100
        print(f"{col}: Original={orig_mean:.2f}, sintetico={synth_mean:.2f}, diff={diff_pct:.1f}%")

    # 2. DIstribuciones de categóricas
    print("\n2. Distribuciones categoricas")
    for col in ['dementia type', 'gender', 'ethnicity', 'dementia']:
        print(f"\n{col}")
        orig_dist = original[col].value_counts(normalize=True)
        synth_dist = synthetic[col].value_counts(normalize=True)

        for val in orig_dist.index:
            orig_pct = orig_dist[val] * 100
            synth_pct = synth_dist.get(val, 0) * 100
            print(f" {val}: original={orig_pct:.1f}%, sintetico={synth_pct:.1f}%")

    # 3. Correlaciones clave

    print("\n3. Correlaciones principales:")
    key_cols = ['f0_mean', 'articulation_rate', 'HNRdBACF_sma3nz_amean', 'dementia']
    
    orig_corr = original[key_cols].corr()
    synth_corr = synthetic[key_cols].corr()
    
    print("Correlación dementia-f0_mean:")
    print(f"  Original: {orig_corr.loc['dementia', 'f0_mean']:.3f}")
    print(f"  Sintético: {synth_corr.loc['dementia', 'f0_mean']:.3f}")
    
    return True

In [35]:
validate_augmented_data(df, synthetic_data)

validación de datos médicos
Estadisticas por variable
duracion_s: Original=56.02, sintetico=56.06, diff=0.1%
rms_mean: Original=0.09, sintetico=0.09, diff=1.5%
rms_std: Original=0.06, sintetico=0.06, diff=0.3%
dementia: Original=0.37, sintetico=0.48, diff=29.9%
f0_mean: Original=178.47, sintetico=175.37, diff=1.7%
f0_std: Original=48.84, sintetico=46.96, diff=3.8%
f0_range: Original=300.61, sintetico=290.51, diff=3.4%
articulation_rate: Original=1.85, sintetico=1.85, diff=0.1%
silence_segments_n: Original=54.00, sintetico=53.91, diff=0.2%
silence_dur_mean_s: Original=0.28, sintetico=0.28, diff=1.6%

2. Distribuciones categoricas

dementia type
 no dementia: original=40.8%, sintetico=18.8%
 Alzheimer: original=27.5%, sintetico=11.2%
 Dementia: original=24.3%, sintetico=12.8%
 Lewy body: original=5.0%, sintetico=6.4%
 Parkinson: original=1.4%, sintetico=5.0%
 Primary progressive aphasia: original=0.9%, sintetico=5.2%

gender
 male: original=85.6%, sintetico=47.7%
 female: original=14.4%, sintetico=15.2%

ethnicity
 Caucasian/White: original=83.3%, sintetico=45.0%
 Black/African American: original=13.9%, sintetico=7.1%
 Indian Subcontinent: original=1.9%, sintetico=5.9%
 Asian: original=0.5%, sintetico=0.1%
 Hispanic: original=0.5%, sintetico=6.3%

dementia
 0: original=62.9%, sintetico=51.8%
 1: original=37.1%, sintetico=48.2%

3. Correlaciones principales:
Correlación dementia-f0_mean:
  Original: 0.025
  Sintético: 0.080

True

In [36]:

def validate_augmented_data(original, synthetic):
    """
    Validate synthetic medical data against original data.
    
    Parameters:
    - original: pd.DataFrame - original dataset
    - synthetic: pd.DataFrame - synthetic dataset
    
    Returns:
    - pd.DataFrame with columns:
        type: type of metric ('numeric_mean', 'categorical', 'correlation')
        variable: column name or correlation pair
        category: category level (for categorical) or NaN
        original: original value (mean, proportion, correlation)
        synthetic: synthetic value
        diff_pct: percent difference (only for numeric means, else NaN)
    """
    rows = []
    
    # 1. Numeric descriptive statistics (first 10 numeric columns)
    numeric_cols = original.select_dtypes(include=[np.number]).columns[:10]
    for col in numeric_cols:
        orig_mean = original[col].mean()
        synth_mean = synthetic[col].mean()
        # Avoid division by zero if original mean is 0
        if orig_mean != 0:
            diff_pct = abs(orig_mean - synth_mean) / orig_mean * 100
        else:
            diff_pct = np.nan
        rows.append({
            'type': 'numeric_mean',
            'variable': col,
            'category': np.nan,
            'original': orig_mean,
            'synthetic': synth_mean,
            'diff_pct': diff_pct
        })
    
    # 2. Categorical distributions
    cat_cols = ['dementia type', 'gender', 'ethnicity', 'dementia']
    for col in cat_cols:
        if col not in original.columns or col not in synthetic.columns:
            continue
        orig_dist = original[col].value_counts(normalize=True)
        synth_dist = synthetic[col].value_counts(normalize=True)
        # Union of all categories present in either dataset
        all_cats = set(orig_dist.index) | set(synth_dist.index)
        for cat in all_cats:
            orig_pct = orig_dist.get(cat, 0) * 100
            synth_pct = synth_dist.get(cat, 0) * 100
            rows.append({
                'type': 'categorical',
                'variable': col,
                'category': cat,
                'original': orig_pct,
                'synthetic': synth_pct,
                'diff_pct': abs(orig_pct - synth_pct)   # absolute percentage point difference
            })
    
    # 3. Key correlations
    key_cols = ['f0_mean', 'articulation_rate', 'HNRdBACF_sma3nz_amean', 'dementia']
    # Ensure all columns exist
    key_cols = [c for c in key_cols if c in original.columns and c in synthetic.columns]
    if len(key_cols) >= 2:
        orig_corr = original[key_cols].corr()
        synth_corr = synthetic[key_cols].corr()
        # We'll report the correlation between dementia and each other key column
        if 'dementia' in key_cols:
            for col in key_cols:
                if col == 'dementia':
                    continue
                orig_val = orig_corr.loc['dementia', col]
                synth_val = synth_corr.loc['dementia', col]
                rows.append({
                    'type': 'correlation',
                    'variable': f'dementia_{col}',
                    'category': np.nan,
                    'original': orig_val,
                    'synthetic': synth_val,
                    'diff_pct': abs(orig_val - synth_val) * 100   # absolute difference in correlation (as percentage points)
                })
    
    # Create DataFrame
    result_df = pd.DataFrame(rows)
    
    # Optional: keep the original print statements for immediate feedback
    print("Validación de datos médicos")
    print("\nEstadísticas por variable:")
    for col in numeric_cols:
        row = result_df[(result_df['type']=='numeric_mean') & (result_df['variable']==col)].iloc[0]
        print(f"{col}: Original={row['original']:.2f}, Sintético={row['synthetic']:.2f}, diff={row['diff_pct']:.1f}%")
    
    print("\nDistribuciones categóricas:")
    for col in cat_cols:
        print(f"\n{col}")
        cat_rows = result_df[(result_df['type']=='categorical') & (result_df['variable']==col)]
        for _, row in cat_rows.iterrows():
            print(f" {row['category']}: original={row['original']:.1f}%, sintético={row['synthetic']:.1f}%")
    
    print("\nCorrelaciones principales:")
    corr_rows = result_df[result_df['type']=='correlation']
    for _, row in corr_rows.iterrows():
        print(f"{row['variable']}: Original={row['original']:.3f}, Sintético={row['synthetic']:.3f}, diff={row['diff_pct']:.2f}%")
    
    return result_df

In [37]:
dcluster = validate_augmented_data(df, synthetic_data)
dcluster

Validación de datos médicos

Estadísticas por variable:
duracion_s: Original=56.02, Sintético=56.06, diff=0.1%
rms_mean: Original=0.09, Sintético=0.09, diff=1.5%
rms_std: Original=0.06, Sintético=0.06, diff=0.3%
dementia: Original=0.37, Sintético=0.48, diff=29.9%
f0_mean: Original=178.47, Sintético=175.37, diff=1.7%
f0_std: Original=48.84, Sintético=46.96, diff=3.8%
f0_range: Original=300.61, Sintético=290.51, diff=3.4%
articulation_rate: Original=1.85, Sintético=1.85, diff=0.1%
silence_segments_n: Original=54.00, Sintético=53.91, diff=0.2%
silence_dur_mean_s: Original=0.28, Sintético=0.28, diff=1.6%

Distribuciones categóricas:

dementia type
 Lewy body: original=5.0%, sintético=6.4%
 Parkinson: original=1.4%, sintético=5.0%
 Alzheimer: original=27.5%, sintético=11.2%
 Dementia: original=24.3%, sintético=12.8%
 no dementia: original=40.8%, sintético=18.8%
 Primary progressive aphasia: original=0.9%, sintético=5.2%
 Unknown: original=0.0%, sintético=40.6%

gender
 female: original=14.4%, sintético=15.2%
 male: original=85.6%, sintético=47.7%
 Unknown: original=0.0%, sintético=37.1%

ethnicity
 Caucasian/White: original=83.3%, sintético=45.0%
 Hispanic: original=0.5%, sintético=6.3%
 Asian: original=0.5%, sintético=0.1%
 Black/African American: original=13.9%, sintético=7.1%
 Unknown: original=0.0%, sintético=35.6%
 Indian Subcontinent: original=1.9%, sintético=5.9%

dementia
 0: original=62.9%, sintético=51.8%
 1: original=37.1%, sintético=48.2%

Correlaciones principales:
dementia_f0_mean: Original=0.025, Sintético=0.080, diff=5.58%
dementia_articulation_rate: Original=-0.015, Sintético=-0.013, diff=0.15%
dementia_HNRdBACF_sma3nz_amean: Original=0.049, Sintético=0.083, diff=3.31%

,type,variable,category,original,synthetic,diff_pct
0,numeric_mean,duracion_s,NaN,56.019615,56.055137,0.063411
1,numeric_mean,rms_mean,NaN,0.089943,0.088552,1.546447
2,numeric_mean,rms_std,NaN,0.061699,0.061505,0.315503
3,numeric_mean,dementia,NaN,0.371105,0.482200,29.936336
4,numeric_mean,f0_mean,NaN,178.469345,175.367931,1.737786
5,numeric_mean,f0_std,NaN,48.843398,46.964070,3.847660
6,numeric_mean,f0_range,NaN,300.610748,290.512940,3.359097
7,numeric_mean,articulation_rate,NaN,1.847707,1.845993,0.092736
8,numeric_mean,silence_segments_n,NaN,53.997167,53.911997,0.157731
9,numeric_mean,silence_dur_mean_s,NaN,0.281062,0.276447,1.642125
10,categorical,dementia type,Lewy body,5.045872,6.380000,1.334128
11,categorical,dementia type,Parkinson,1.376147,4.960000,3.583853
12,categorical,dementia type,Alzheimer,27.522936,11.160000,16.362936
13,categorical,dementia type,Dementia,24.311927,12.840000,11.471927
14,categorical,dementia type,no dementia,40.825688,18.780000,22.045688
15,categorical,dementia type,Primary progressive aphasia,0.917431,5.240000,4.322569
16,categorical,dementia type,Unknown,0.000000,40.640000,40.640000
17,categorical,gender,female,14.351852,15.160000,0.808148
18,categorical,gender,male,85.648148,47.740000,37.908148
19,categorical,gender,Unknown,0.000000,37.100000,37.100000
20,categorical,ethnicity,Caucasian/White,83.333333,45.040000,38.293333
21,categorical,ethnicity,Hispanic,0.462963,6.300000,5.837037
22,categorical,ethnicity,Asian,0.462963,0.080000,0.382963
23,categorical,ethnicity,Black/African American,13.888889,7.100000,6.788889
24,categorical,ethnicity,Unknown,0.000000,35.600000,35.600000
25,categorical,ethnicity,Indian Subcontinent,1.851852,5.880000,4.028148
26,categorical,dementia,0,62.889518,51.780000,11.109518
27,categorical,dementia,1,37.110482,48.220000,11.109518
28,correlation,dementia_f0_mean,NaN,0.024626,0.080413,5.578697
29,correlation,dementia_articulation_rate,NaN,-0.014581,-0.013113,0.146772
30,correlation,dementia_HNRdBACF_sma3nz_amean,NaN,0.049397,0.082513,3.311604

In [13]:
data_aumentada_comp = pd.concat([df, synthetic_data ], ignore_index=True)

In [14]:
data_aumentada_comp.head()

,duracion_s,rms_mean,rms_std,dementia,dementia type,gender,ethnicity,f0_mean,f0_std,f0_range,...,propn_ratio,noun_pron_ratio,syntax_depth,std_words_per_sent,mean_word_length,std_word_length,function_ratio,duration,pause_prob,wpm
0,71.019688,0.071390,0.050389,1,Alzheimer,male,Caucasian/White,174.444418,51.103025,311.055420,...,0.037975,0.465517,7.666667,75.330383,3.789030,2.132184,0.611814,72.76,0.263634,195.437053
1,47.000000,0.144582,0.090372,1,Dementia,female,Black/African American,292.169978,115.242586,659.783615,...,0.000000,0.500000,5.500000,13.379088,3.810811,1.850315,0.628378,47.04,0.122493,188.775510
2,38.000000,0.123960,0.079574,1,Dementia,female,Black/African American,238.856939,58.060892,352.463261,...,0.000000,0.655172,5.428571,12.290697,3.625000,1.952562,0.585938,38.40,0.000328,200.000000
3,90.000000,0.061281,0.049997,1,Dementia,female,Black/African American,255.297147,68.547493,638.292396,...,0.000000,1.146341,5.357143,9.598044,4.003597,2.092292,0.575540,89.00,0.002673,187.415730
4,55.000000,0.060310,0.051383,1,Dementia,male,Caucasian/White,134.696479,38.961565,243.928633,...,0.067073,1.000000,4.500000,8.890444,4.286585,2.216252,0.640244,55.00,0.149834,178.909091

In [15]:
data_aumentada_comp.shape

(5353, 74)

In [17]:
data_aumentada_comp.to_csv('data_aumentada_v1.csv')

****

## CopulaGAN

In [38]:
import numpy as np
from scipy import stats
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import StandardScaler

In [39]:
def generate_with_copula(df, n_samples=2000):
        """
        Copulas gaussianas
        """

        df_filled = df.copy()

        # imputar categoricas
        categorical_cols = ['dementia', 'dementia type', 'gender', 'ethnicity']
        for col in categorical_cols:
            if col in df_filled.columns:
                df_filled[col] = df_filled[col].fillna('Unknown')

        # imputar numericas con la mediana
        numeric_cols = df_filled.select_dtypes(include=[np.number]).columns
        for col in numeric_cols:
            df_filled[col] = df_filled[col].fillna(df_filled[col].median())
    
        # identificar variables continuos 
        continuous_cols = df_filled.select_dtypes(include=[np.number]).columns.tolist()
        # excluir columnas que no son realmente continuasl
        exclude_cols = ['dementia'] + categorical_cols
        continuous_cols = [c for c in continuous_cols if c not in exclude_cols]

        print(f"procesando {len(continuous_cols)} varables continuas")

        # transformar variables continuas a normales

    
        transformed_data = []
        transformers = {}

        for col in continuous_cols:
           try:
                # usar transformacion de potencia para normalizar
                pt = PowerTransformer(method='yeo-johnson')
                transformed = pt.fit_transform(df_filled[[col]]) 
                transformed_data.append(transformed.flatten())
                transformers[col] = pt
           except Exception as e:
                print(f"Error transformando {col} : {e}")
                # si falla la tranformacion usar estandarizacion simple
                scaler = StandardScaler()
                tranformed = scaler.fit_transform(df_filled[[col]])
                transformed_data.append(transformed.flatten())
                transformers[col] = scaler
           
        #  Asegurar que los arrays tenga la misma longitud
        min_length = min(len(arr) for arr in transformed_data)
        if min_length < len(df_filled):
            print(f"advertencia: algunas columnas tenian NaN. Usando {min_length} muestras validas")


        # recordar todos los arrays a la misma longitud 
        transformed_data = [arr[:min_length] for arr in transformed_data]


        # calcular la matriz de correlacion
        transformed_matrix = np.column_stack(transformed_data)
        corr_matrix = np.corrcoef(transformed_matrix, rowvar=False)

        # generar datos normales multivariados
        mean_vector = np.zeros(len(continuous_cols))
        try:
            synthetic_normal = np.random.multivariate_normal(mean_vector, 
                                                         corr_matrix, 
                                                         n_samples)

        except Exception as e:
            print(f"eror en mumtivarite_normal: {e}")
            print("Generando variables independientes como fallback")
            synthetic_normal = np.random.randn(n_samples, len(continuous_cols))



    
        # Transformar de vuelta a la distribucion original
        synthetic_df = pd.DataFrame()

        for i, col in enumerate(continuous_cols):
            pt = transformers[col]
            synthetic_col = pt.inverse_transform(synthetic_normal[:, i].reshape(-1, 1))
            synthetic_df[col] = synthetic_col.flatten()

        # agregar variables categoricas
        for cat_col in categorical_cols + ['dementia']:
            if cat_col in df_filled.columns:
                value_counts = df_filled[cat_col].value_counts(normalize=True)

                if len(value_counts) > 0:
            # samplear de distribucion empirica
       
                    synthetic_df[cat_col] = np.random.choice(
                                    value_counts.index.tolist(),
                                    size=n_samples,
                                    p=value_counts.values)
        else:
            synthetic_df[cat_col] = df_filled[cat_col].mode()[0] if len(df_filled[cat_col].mode()) > 0 else 'Unknown'

        for col in categorical_cols:
            if col in synthetic_df.columns:
                synthetic_df[col] = synthetic_df[col].astype(str)
        if 'dementia' in synthetic_df.columns:
            synthetic_df['dementia'] = synthetic_df['dementia'].astype(int)

        print(f"Datos generados: {synthetic_df.shape}")

    
        return synthetic_df

In [40]:
data_copula = generate_with_copula(df)
data_copula.head()

procesando 70 varables continuas
Datos generados: (2000, 74)

,duracion_s,rms_mean,rms_std,f0_mean,f0_std,f0_range,articulation_rate,silence_segments_n,silence_dur_mean_s,silence_ratio_rms,...,mean_word_length,std_word_length,function_ratio,duration,pause_prob,wpm,dementia,dementia type,gender,ethnicity
0,112.441933,0.085655,0.061826,132.614485,38.533583,268.792227,2.051580,114.735072,0.298082,-0.038617,...,4.125818,2.759257,0.703589,114.479147,-0.062814,129.895398,0,no dementia,male,Caucasian/White
1,10.174921,0.146490,0.089174,178.375550,82.301930,274.780598,2.338567,5.591024,0.448191,NaN,...,3.645223,1.699591,0.578712,14.301604,0.228810,132.711440,0,no dementia,Unknown,Caucasian/White
2,92.817704,0.085214,0.049355,237.280122,66.703894,530.393934,1.962066,122.590275,0.197355,-0.046654,...,3.778772,2.112460,0.536747,89.373133,0.076410,150.969087,0,Alzheimer,male,Caucasian/White
3,50.793531,0.099657,0.079062,190.158573,40.968400,216.621076,1.792133,50.502122,0.256979,-0.024007,...,4.101414,2.108838,0.630283,46.652842,0.183997,128.658333,0,Unknown,Unknown,Unknown
4,37.450149,0.364231,0.164388,352.698087,141.900151,800.511506,1.828856,23.334554,0.311136,NaN,...,3.604392,1.785155,0.582888,41.006805,0.280958,147.492738,0,Unknown,male,Caucasian/White

In [24]:
data_copula.dementia.value_counts()

dementia
0    2000
Name: count, dtype: int64

In [42]:
dcopulas = validate_augmented_data(df, data_copula)
dcopulas

Validación de datos médicos

Estadísticas por variable:
duracion_s: Original=56.02, Sintético=56.32, diff=0.5%
rms_mean: Original=0.09, Sintético=0.09, diff=0.2%
rms_std: Original=0.06, Sintético=0.06, diff=0.3%
dementia: Original=0.37, Sintético=0.00, diff=100.0%
f0_mean: Original=178.47, Sintético=179.79, diff=0.7%
f0_std: Original=48.84, Sintético=49.98, diff=2.3%
f0_range: Original=300.61, Sintético=313.27, diff=4.2%
articulation_rate: Original=1.85, Sintético=1.85, diff=0.1%
silence_segments_n: Original=54.00, Sintético=54.57, diff=1.1%
silence_dur_mean_s: Original=0.28, Sintético=0.28, diff=0.9%

Distribuciones categóricas:

dementia type
 Lewy body: original=5.0%, sintético=3.8%
 Parkinson: original=1.4%, sintético=0.7%
 Alzheimer: original=27.5%, sintético=16.2%
 Dementia: original=24.3%, sintético=15.8%
 no dementia: original=40.8%, sintético=24.3%
 Primary progressive aphasia: original=0.9%, sintético=0.6%
 Unknown: original=0.0%, sintético=38.8%

gender
 female: original=14.4%, sintético=8.5%
 male: original=85.6%, sintético=51.0%
 Unknown: original=0.0%, sintético=40.5%

ethnicity
 Caucasian/White: original=83.3%, sintético=51.0%
 Hispanic: original=0.5%, sintético=0.2%
 Asian: original=0.5%, sintético=0.6%
 Black/African American: original=13.9%, sintético=8.5%
 Unknown: original=0.0%, sintético=39.0%
 Indian Subcontinent: original=1.9%, sintético=0.7%

dementia
 0: original=62.9%, sintético=100.0%
 1: original=37.1%, sintético=0.0%

Correlaciones principales:
dementia_f0_mean: Original=0.025, Sintético=nan, diff=nan%
dementia_articulation_rate: Original=-0.015, Sintético=nan, diff=nan%
dementia_HNRdBACF_sma3nz_amean: Original=0.049, Sintético=nan, diff=nan%

,type,variable,category,original,synthetic,diff_pct
0,numeric_mean,duracion_s,NaN,56.019615,56.319882,0.536004
1,numeric_mean,rms_mean,NaN,0.089943,0.089764,0.199666
2,numeric_mean,rms_std,NaN,0.061699,0.061491,0.337350
3,numeric_mean,dementia,NaN,0.371105,0.000000,100.000000
4,numeric_mean,f0_mean,NaN,178.469345,179.789760,0.739855
5,numeric_mean,f0_std,NaN,48.843398,49.980694,2.328455
6,numeric_mean,f0_range,NaN,300.610748,313.265348,4.209630
7,numeric_mean,articulation_rate,NaN,1.847707,1.846153,0.084100
8,numeric_mean,silence_segments_n,NaN,53.997167,54.571583,1.063788
9,numeric_mean,silence_dur_mean_s,NaN,0.281062,0.278610,0.872486
10,categorical,dementia type,Lewy body,5.045872,3.750000,1.295872
11,categorical,dementia type,Parkinson,1.376147,0.650000,0.726147
12,categorical,dementia type,Alzheimer,27.522936,16.150000,11.372936
13,categorical,dementia type,Dementia,24.311927,15.800000,8.511927
14,categorical,dementia type,no dementia,40.825688,24.300000,16.525688
15,categorical,dementia type,Primary progressive aphasia,0.917431,0.600000,0.317431
16,categorical,dementia type,Unknown,0.000000,38.750000,38.750000
17,categorical,gender,female,14.351852,8.500000,5.851852
18,categorical,gender,male,85.648148,51.000000,34.648148
19,categorical,gender,Unknown,0.000000,40.500000,40.500000
20,categorical,ethnicity,Caucasian/White,83.333333,51.000000,32.333333
21,categorical,ethnicity,Hispanic,0.462963,0.200000,0.262963
22,categorical,ethnicity,Asian,0.462963,0.600000,0.137037
23,categorical,ethnicity,Black/African American,13.888889,8.500000,5.388889
24,categorical,ethnicity,Unknown,0.000000,39.000000,39.000000
25,categorical,ethnicity,Indian Subcontinent,1.851852,0.700000,1.151852
26,categorical,dementia,0,62.889518,100.000000,37.110482
27,categorical,dementia,1,37.110482,0.000000,37.110482
28,correlation,dementia_f0_mean,NaN,0.024626,NaN,NaN
29,correlation,dementia_articulation_rate,NaN,-0.014581,NaN,NaN
30,correlation,dementia_HNRdBACF_sma3nz_amean,NaN,0.049397,NaN,NaN

****

## Mixtura Gaussiana

In [43]:
import pandas as pd
import numpy as np
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer, KNNImputer
import warnings
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
warnings.filterwarnings('ignore')

In [44]:
class GMMDataGenerator:
    def __init__(self, n_components=None, covariance_type='full', imputation_strategy='median',
                random_state=42):
        """ 
        Generador de datos usando gaussian misture models GMM
        """
        self.n_components = n_components
        self.covariance_type = covariance_type
        self.imputation_strategy = imputation_strategy
        self.random_state = random_state
        self.label_encoders = {}
        self.label_encoders = {}
        self.gmm = None
        self.imputer = None
        np.random.seed(random_state)

    def _handle_missing_values(self, df):
        """ 
        Manejo avanzado de valores faltantes
        """

        df_clean = df.copy()

        # identificar columnas con NaN
        nan_columns = df_clean.columns[df_clean.isna().any()].tolist()

        if not nan_columns:
            print("No se encontraron valoes NaN en el dataset")
            return df_clean

        print(f"columnas con NaN: {len(nan_columns)}")

        # separar columnas categoricas y numericas
        categorical_cols = ['dementia type', 'gender', 'ethnicity']
        numerical_cols = [col for col in df_clean.columns
                         if col not in categorical_cols and np.issubdtype(df_clean[col].dtype, np.number)]
        
        # manejo de NaN en categoricas
        for col in categorical_cols:
            if col in df_clean.columns and col in nan_columns:
                nan_count = df_clean[col].isna().sum()
                print(f"- {col} : {nan_count} NaN ({nan_count/len(df_clean)*100:.1f}%)")

                # usar moda para imputar
                if not df_clean[col].mode().empty:
                    mode_val = df_clean[col].mode()[0]
                    df_clean[col] = df_clean[col].fillna(mode_val)
                    print(f" rellenado con '{mode_val}'")
                else:
                    df_clean[col] = df_clean[col].fillna("Unknown")
                    print(f" rellenado con unknowm")
                    
        # manejo de nan en numericas
        numerical_nan_cols = [col for col in numerical_cols if col in nan_columns]

        if numerical_nan_cols:
            print(f"\n Imputando {len(numerical_nan_cols)} columnas numericas")

            if self.imputation_strategy == 'knn':
                self.imputer = KNNImputer(n_neighbors=5)
            elif self.imputation_strategy == 'iterative':
                self.imputer = IterativeImputer(max_iter=10, random_state= self.random_state)
            else:
                self.imputer = SimpleImputer(strategy=self.imputation_strategy)

            # imputar solo columnas numericas
            df_clean[numerical_nan_cols] = self.imputer.fit_transform(df_clean[numerical_nan_cols])
            print(f"Estrategia: {self.imputation_strategy}")

        # verificar que no queden NaN
        remaining_nan = df_clean.isna().sum().sum()
        if remaining_nan > 0:
            print(f"Adventencia: {remaining_nan} valores NaN restantes, usando fillna(0)")
            df_clean = df_clean.fillna(0)

        return df_clean
            
          
    def _encode_categorical_variables(self, df):

        """
        codigicar variables categoricas preservando mapeos
        """
        df_encoded = df.copy()
        categorical_cols = ['dementia type', 'gender', 'ethnicity']

        for col in categorical_cols:
            if col in df_encoded.columns:
                unique_vals = df_encoded[col].unique()

                le = LabelEncoder()
                df_encoded[col] = le.fit_transform(df_encoded[col])
                self.label_encoders[col] = {
                    'encoder': le,
                    'clases': le.classes_,
                    'original_values':unique_vals
                }

                print(f"{col}: {len(unique_vals)} categorias codificadas")
                
        return df_encoded


    def _decode_categorical_variables(self, df_encoded):
         """ 
         Decodificar varaibles categoricas usando los mapeos guardados
         """
         df_decoded = df_encoded.copy()

         for col, encoder_info, in self.label_encoders.items():
             if col in df_encoded.columns:
                 le = encoder_info['encoder']

                 # redondear valores continuos a enteros
                 df_decoded[col] = df_decoded[col].round().astype(int)

                 n_clases = len(le.classes_)
                 df_decoded[col] = df_decoded[col].clip(0, n_clases -1)

                 # decodificar
                 try:
                     df_decoded[col] = le.inverse_transform(df_decoded[col])
                 except ValueError as e:
                     print(f"Error decodificado {col}:{e}")
                     print(f"Valores unicos en datos codificados: {df_decoded[col].unique()}")
                     print(f"Clases del encoder: {le.classes_}") 

                     # fallback mapear el valor mas cercano
                     def safe_inverse(val):
                         try:
                             return le.inverse_transform([val])[0]
                         except:
                              return le.classes_[0]

                     df_decoded[col] = df_decoded[col].apply(safe_inverse)

         return df_decoded

    def fit(self, df, target_col='dementia'):
          """
          Ajustar el modelo GMM a los datos
          """
          # manejo valores faltantes
          df_clean = self._handle_missing_values(df)

          # separar caracteristicas y target si exist
          if target_col in df_clean.columns:
              X = df_clean.drop(columns=[target_col])
              self.y =df_clean[target_col]

              print(f"variable objetivo '{target_col}' separada")
          else:
              X = df_clean
              self.y = None
              print("No se encontro variable objetivo")
              
          # codificar categoricas
          X_encoded = self._encode_categorical_variables(X)

          # determinar numero de componentes
          if self.n_components is None:
              n_samples = len(X_encoded)
              n_features = X_encoded.shape[1]

              # regla general: sqrt(n_samples) o n_samples//10
              self.n_components = max(2, min(10, int(np.sqrt(n_samples)), n_samples //10))
              print(f" numero de componentes automatico: {self.n_components}")
          else:
              print(f" numero de componentes especificado: {self.n_components}")

          # entrena GMM
          self.gmm = GaussianMixture(
              n_components = self.n_components,
              covariance_type = self.covariance_type,
              random_state = self.random_state,
              init_params='kmeans',
              max_iter = 200,
              tol=1e-3,
              verbose=1
          )
              
          self.gmm.fit(X_encoded)
          print(f"covergio:{self.gmm.converged_}")
          print(f"iteraciones:{self.gmm.n_iter_}")
          print(f"score: {self.gmm.score(X_encoded):.4f}")

          # guardar los datos transformados para referencia
          self.X_encoded = X_encoded
          self.X_original = X

          print(f"Modelo GMM ajustado exitosamente")

          return self


    def generate_samples(self, n_samples=1000, include_target=True, target_distribution='match'):
        """
        Generar muestras sintéticas
        
        Parameters:
        -----------
        n_samples : int
            Número de muestras a generar
        include_target : bool
            Si True, incluye la variable objetivo en la salida
        target_distribution : str
            'match' : mantiene distribución original de target
            'balanced' : balancea las clases
            'random' : asigna aleatoriamente según probabilidades originales
        """

        if self.gmm is None:
            raise ValueError("El modelo GMM no ha sido ajustado")

        # generar muestras del GMM
        synthetic_encoded, cluster_labels = self.gmm.sample(n_samples)
        synthetic_encoded = synthetic_encoded.astype(float)

        # crear dataframe
        synthetic_df = pd.DataFrame(synthetic_encoded, columns=self.X_encoded.columns)

        # decodificar variables categoricas
        synthetic_df = self._decode_categorical_variables(synthetic_df)

        # asignar variable objetivo si es necesario
        if include_target and self.y is not None:
            if target_distribution == 'match':
                # mantener distribucion original por cluster
                synthetic_df['dementia'] = self._assign_target_by_cluster(
                    cluster_labels, self.gmm.weights_
                )
            elif target_distribution == 'balanced':
                # asignar clases balanceadas
                n_clases =lent(np.unique(self.y))
                synthetic_df['dementia'] = np.random.randint(0, n_clases, n_samples)
            else:
                # asignar segun distribucion original
                probs = np.bincount(self.y)/ len(self.y)
                synthetic_df['dementia'] = np.random.choice(len(probs), n_samples, p=probs)
                
        return synthetic_df


    def _assign_target_by_cluster(self, cluster_labels, cluster_weights):
            """ 
            Asignar valores de target basados en distribucion por cluster
            """

            target_values = []

            # para cada cluster, calcular distribucion de target
            cluster_target_dist = {}
            for cluster in range(self.n_components):
                # encontrar muestras originales en est cluster
                cluster_probs = self.gmm.predict_proba(self.X_encoded)
                cluster_mask = cluster_probs.argmax(axis=1) == cluster

                if cluster_mask.sum() > 0:
                    # distribucion de target en este cluster
                    cluster_y = self.y[cluster_mask]
                    unique, counts = np.unique(cluster_y, return_counts=True)
                    dist = counts / counts.sum()
                    cluster_target_dist[cluster] = (unique, dist)
                else:
                    #si no hay muestras, usar distribucion global
                    unique, counts = np.unique(self.y, return_counts=True)
                    dist = counts / counts.sum()
                    cluster_target_dist[cluster] = (unique, dist)

            # asignar target a cada muestra sintetica
            for cluster in cluster_labels:
                unique, dist = cluster_target_dist[cluster]
                target_values.append(np.random.choice(unique, p=dist))

            return np.array(target_values)

    def validate_generated_data(self, synthetic_df, original_df=None, n_tests=5):
        """ 
        validar calidad de datos generados
        """

        if original_df is None:
            original_df = self.X_original

        # 1. estatisticas basicas
        print(f"\n estadisticas basicas")
        print(f" original: {len(original_df)} muestras")
        print(f" sintetico: {len(synthetic_df)} muestras")

        # 2. Distribucion de variables categoricas

        print("\n distribuciones de variables categoricas:")
        cat_cols = ['dementia type', 'gender', 'ethnicity', 'dementia']

        for col in cat_cols:
            if col in synthetic_df.columns and col in original_df.columns:
                print(f"\n {col}")
                orig_dist = original_df[col].value_counts(normalize=True).sort_index()
                synth_dist = synthetic_df[col].value_counts(normalize=True).sort_index()

                for val in orig_dist.index[:5]:
                    orig_pct = orig_dist[val] * 100
                    synth_val = synth_dist.index[synth_dist.index == val]
                    if len(synth_val) > 0:
                        synth_pct = synth_dist[synth_val[0]] * 100
                    else:
                        synth_pct = 0
                    print(f"{val}: orignal={orig_pct:.1f}%, sintetico={synth_pct:1f}%")

        # 3. media y desviacion estandar de variables numericas clave
        print(" variables numericas clave: ")

        num_cols = ['f0_mean', 'articulation_rate', 'HNRdBACF_sma3nz_amean']

        for col in num_cols:
            if col in synthetic_df.columns and col in original_df.columns:
                print(f"{col}:")
                orig_mean = original_df[col].mean()
                synth_mean = synthetic_df[col].mean()
                orig_std = original_df[col].std()
                synth_std = synthetic_df[col].std()

                print(f"Media: original={orig_mean:.4f}, sintetico={synth_mean:.4f}")
                print(f"Std: original={orig_std:.4f}, sintetico={synth_std:.4f}")


                # diferencia porcentual
                mean_diff_pct = abs(orig_mean - synth_mean) / orig_mean * 100
                std_diff_pct = abs(orig_std - synth_mean) / orig_std * 100
                print(f" Dif media: {mean_diff_pct:.1f}%")
                print(f" Dif std: {std_diff_pct:.1f}%")
        return True

In [45]:
def main():

    # crear instancia del generador
    generator = GMMDataGenerator(
        n_components=5, 
        covariance_type='full',
        imputation_strategy='median',
        random_state = 42
    )

    # ajuste del modelo
    generator.fit(df, target_col='dementia')

    # generar datos sinteticos
    print(f"Generando datos sinteticos")
    synthetic_data = generator.generate_samples(n_samples=2000, 
                                                include_target=True, 
                                                target_distribution='match')
    # validar datos generados
    generator.validate_generated_data(synthetic_data)

    # mostrar primeros registros
    print("\nPrimeras 10 filas de datos sinteticos:")
    print(synthetic_data.head(10))

    # gurdar datos si es necesario
    synthetic_data.to_csv('datos_synteticos_gmm.csv', index=False)
    print("\nDatos guardatos en 'datos_synteticos_gmm.csv'")

    return synthetic_data

# ejecucion directa
if __name__ == "__main__":
    synthetic_data = main()

columnas con NaN: 19
- dementia type : 135 NaN (38.2%)
 rellenado con 'no dementia'
- gender : 137 NaN (38.8%)
 rellenado con 'male'
- ethnicity : 137 NaN (38.8%)
 rellenado con 'Caucasian/White'

 Imputando 16 columnas numericas
Estrategia: median
variable objetivo 'dementia' separada
dementia type: 6 categorias codificadas
gender: 2 categorias codificadas
ethnicity: 5 categorias codificadas
 numero de componentes especificado: 5
Initialization 0
Initialization converged.
covergio:True
iteraciones:2
score: 6.3783
Modelo GMM ajustado exitosamente
Generando datos sinteticos

 estadisticas basicas
 original: 353 muestras
 sintetico: 2000 muestras

 distribuciones de variables categoricas:

 dementia type
Alzheimer: orignal=17.0%, sintetico=7.350000%
Dementia: orignal=15.0%, sintetico=9.150000%
Lewy body: orignal=3.1%, sintetico=14.100000%
Parkinson: orignal=0.8%, sintetico=19.200000%
Primary progressive aphasia: orignal=0.6%, sintetico=18.050000%

 gender
female: orignal=8.8%, sintetico=6.700000%
male: orignal=91.2%, sintetico=93.300000%

 ethnicity
Asian: orignal=0.3%, sintetico=0.050000%
Black/African American: orignal=8.5%, sintetico=12.400000%
Caucasian/White: orignal=89.8%, sintetico=81.350000%
Hispanic: orignal=0.3%, sintetico=6.200000%
Indian Subcontinent: orignal=1.1%, sintetico=0.000000%
 variables numericas clave:
f0_mean:
Media: original=178.4693, sintetico=182.0935
Std: original=102.5031, sintetico=104.5617
 Dif media: 2.0%
 Dif std: 77.6%
articulation_rate:
Media: original=1.8477, sintetico=1.8537
Std: original=0.3885, sintetico=0.3817
 Dif media: 0.3%
 Dif std: 377.1%
HNRdBACF_sma3nz_amean:
Media: original=4.7855, sintetico=4.7629
Std: original=1.6729, sintetico=1.6654
 Dif media: 0.5%
 Dif std: 184.7%

Primeras 10 filas de datos sinteticos:
   duracion_s  rms_mean   rms_std                dementia type gender  \
0   72.385521  0.159658  0.073264                     Dementia   male
1   64.910002  0.107623  0.076267  Primary progressive aphasia   male
2   44.599100  0.044158  0.015196                    Parkinson   male
3   93.402187  0.040616  0.038083                    Parkinson   male
4   46.120386  0.095304  0.066085  Primary progressive aphasia   male
5   98.655392  0.036346  0.054722  Primary progressive aphasia   male
6  107.459141  0.046906  0.060059                    Parkinson   male
7   34.523937  0.146544  0.088981                    Parkinson   male
8   29.621788 -0.001958 -0.011590                  no dementia   male
9   58.718625  0.099005  0.055018  Primary progressive aphasia   male

                ethnicity     f0_mean     f0_std    f0_range  \
0         Caucasian/White  300.809199  56.357217  221.620209
1         Caucasian/White    5.942658  34.911429  374.652198
2         Caucasian/White  137.081199  58.720387  381.608416
3         Caucasian/White  232.330590  27.451381  230.356540
4  Black/African American  273.638019  62.717821  318.673480
5         Caucasian/White  213.914776  37.285180  321.894890
6                Hispanic   35.814744  24.146864  380.291104
7         Caucasian/White  124.053469  63.820890  403.830530
8         Caucasian/White  149.000559  26.712774   88.040120
9         Caucasian/White  122.985678   8.987524  328.902208

   articulation_rate  ...  noun_pron_ratio  syntax_depth  std_words_per_sent  \
0           1.922055  ...         1.461125      5.882545           -5.358593
1           1.877263  ...        -0.100913      4.692801           13.140407
2           2.293295  ...         3.080383      4.064586            7.525512
3           1.585221  ...         1.926738      6.736996           19.755519
4           1.926654  ...         2.875614      5.925467           21.553626
5           1.251659  ...         0.192878      0.920804           -2.003983
6           1.468702  ...         1.803518      3.740892            5.625676
7           1.952650  ...         3.191255      3.899989          -13.728868
8           2.326707  ...        -0.109954      4.215257           10.503344
9           1.446629  ...         1.786381      3.192031           -9.503895

   mean_word_length  std_word_length  function_ratio    duration  pause_prob  \
0          4.102241         2.355537        0.592231   67.217880    0.122023
1          3.962556         2.013388        0.461371   68.735450    0.067436
2          4.276533         2.574176        0.514144   46.115914    0.225705
3          3.928936         2.435694        0.584270   88.632297   -0.005937
4          3.906701         1.931494        0.649659   41.373127    0.145736
5          3.912870         2.052374        0.505282   93.138853    0.068323
6          4.168247         2.228092        0.639384  111.992146   -0.021046
7          4.125672         2.242716        0.659493   40.625207    0.217457
8          4.001246         2.267277        0.559879   27.471294    0.327195
9          3.716563         2.082473        0.567082   56.931583    0.120162

          wpm  dementia
0  135.498213         0
1  185.864105         1
2  157.809453         1
3  172.422087         0
4  129.632151         0
5  105.216231         0
6  166.188581         0
7  167.508559         1
8  183.673998         0
9  201.784258         1

[10 rows x 74 columns]

Datos guardatos en 'datos_synteticos_gmm.csv'

In [46]:
dmixtura = validate_augmented_data(df, synthetic_data)
dmixtura

Validación de datos médicos

Estadísticas por variable:
duracion_s: Original=56.02, Sintético=56.40, diff=0.7%
rms_mean: Original=0.09, Sintético=0.09, diff=1.7%
rms_std: Original=0.06, Sintético=0.06, diff=1.6%
dementia: Original=0.37, Sintético=0.37, diff=0.5%
f0_mean: Original=178.47, Sintético=182.09, diff=2.0%
f0_std: Original=48.84, Sintético=48.75, diff=0.2%
f0_range: Original=300.61, Sintético=301.75, diff=0.4%
articulation_rate: Original=1.85, Sintético=1.85, diff=0.3%
silence_segments_n: Original=54.00, Sintético=54.68, diff=1.3%
silence_dur_mean_s: Original=0.28, Sintético=0.28, diff=0.5%

Distribuciones categóricas:

dementia type
 Lewy body: original=5.0%, sintético=14.1%
 Parkinson: original=1.4%, sintético=19.2%
 Alzheimer: original=27.5%, sintético=7.3%
 Dementia: original=24.3%, sintético=9.2%
 no dementia: original=40.8%, sintético=32.1%
 Primary progressive aphasia: original=0.9%, sintético=18.1%

gender
 male: original=85.6%, sintético=93.3%
 female: original=14.4%, sintético=6.7%

ethnicity
 Caucasian/White: original=83.3%, sintético=81.3%
 Hispanic: original=0.5%, sintético=6.2%
 Asian: original=0.5%, sintético=0.1%
 Black/African American: original=13.9%, sintético=12.4%
 Indian Subcontinent: original=1.9%, sintético=0.0%

dementia
 0: original=62.9%, sintético=62.7%
 1: original=37.1%, sintético=37.3%

Correlaciones principales:
dementia_f0_mean: Original=0.025, Sintético=-0.021, diff=4.54%
dementia_articulation_rate: Original=-0.015, Sintético=-0.014, diff=0.03%
dementia_HNRdBACF_sma3nz_amean: Original=0.049, Sintético=-0.016, diff=6.51%

,type,variable,category,original,synthetic,diff_pct
0,numeric_mean,duracion_s,NaN,56.019615,56.395245,0.670534
1,numeric_mean,rms_mean,NaN,0.089943,0.091462,1.688736
2,numeric_mean,rms_std,NaN,0.061699,0.062682,1.592101
3,numeric_mean,dementia,NaN,0.371105,0.373000,0.510687
4,numeric_mean,f0_mean,NaN,178.469345,182.093486,2.030680
5,numeric_mean,f0_std,NaN,48.843398,48.747999,0.195316
6,numeric_mean,f0_range,NaN,300.610748,301.751875,0.379603
7,numeric_mean,articulation_rate,NaN,1.847707,1.853671,0.322770
8,numeric_mean,silence_segments_n,NaN,53.997167,54.683214,1.270523
9,numeric_mean,silence_dur_mean_s,NaN,0.281062,0.279742,0.469833
10,categorical,dementia type,Lewy body,5.045872,14.100000,9.054128
11,categorical,dementia type,Parkinson,1.376147,19.200000,17.823853
12,categorical,dementia type,Alzheimer,27.522936,7.350000,20.172936
13,categorical,dementia type,Dementia,24.311927,9.150000,15.161927
14,categorical,dementia type,no dementia,40.825688,32.150000,8.675688
15,categorical,dementia type,Primary progressive aphasia,0.917431,18.050000,17.132569
16,categorical,gender,male,85.648148,93.300000,7.651852
17,categorical,gender,female,14.351852,6.700000,7.651852
18,categorical,ethnicity,Caucasian/White,83.333333,81.350000,1.983333
19,categorical,ethnicity,Hispanic,0.462963,6.200000,5.737037
20,categorical,ethnicity,Asian,0.462963,0.050000,0.412963
21,categorical,ethnicity,Black/African American,13.888889,12.400000,1.488889
22,categorical,ethnicity,Indian Subcontinent,1.851852,0.000000,1.851852
23,categorical,dementia,0,62.889518,62.700000,0.189518
24,categorical,dementia,1,37.110482,37.300000,0.189518
25,correlation,dementia_f0_mean,NaN,0.024626,-0.020792,4.541849
26,correlation,dementia_articulation_rate,NaN,-0.014581,-0.014258,0.032215
27,correlation,dementia_HNRdBACF_sma3nz_amean,NaN,0.049397,-0.015749,6.514572

****

## Método Bayesiano para Data Augmentation

In [48]:
import pandas as pd
import numpy as np
from scipy.stats import norm, multivariate_normal
from statsmodels.distributions.copula.api import GaussianCopula
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [49]:
# Preprocesamiento similar al anterior
num_cols = [col for col in df.columns if df[col].dtype in ['float64', 'int64'] and col != 'dementia']
cat_cols = ['dementia type', 'gender', 'ethnicity']
target_col = 'dementia'

num_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

cat_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_transformer, num_cols),
        ('cat', cat_transformer, cat_cols)
    ])

# separar por clase para modelar condicionalmente
df_0 = df[df[target_col] == 0].drop(columns=[target_col])
df_1 = df[df[target_col] == 1].drop(columns=[target_col])

X_0 = preprocessor.fit_transform(df_0) 
X_1 = preprocessor.transform(df_1)

# funcion para fit copula por clase

def fit_gaussian_copula(X, epsilon=1e-6):
    if X.shape[0] < 2:
        raise ValueError("need at leat 2 rows to fit a copula")
    # transformar a uniformes
    u = norm.cdf(X)
    u = np.clip(u, epsilon, 1 - epsilon)
    u += np.random.uniform(-1e-8, 1e-8, size=u.shape)
    u = np.clip(u, epsilon, 1 - epsilon)
    # correlacion para gaussian copula
    corr = np.corrcoef(u.T)
    # arreglar NaN
    if not np.all(np.isfinite(corr)):
        print("warning:correlation matrix contained inf/nan")
        # replace nana with 0, inf with +/- 1
        corr = np.nan_to_num(corr, nan=0.0, posinf=1.0, neginf=-1.0)
        corr = np.clip(corr, -1.0, 1.0)
    
    corr = (corr + corr.T) / 2
    # ridge regularization
    corr += 1e-5 * np.eye(corr.shape[0])
    
    # hacerla semidefinida positiva
    eigvals, eigvecs = np.linalg.eigh(corr)
    eigvals = np.maximum(eigvals, 1e-8)
    corr_psd = eigvecs @ np.diag(eigvals) @ eigvecs.T
    # reconstruir matrix
    corr_psd = (corr_psd + corr_psd.T) / 2
    corr_psd = np.clip(corr_psd, -1.0, 1.0)
    copula = GaussianCopula(corr=corr_psd, allow_singular=True)
    return copula, u

copula_0, u_0 = fit_gaussian_copula(X_0)
copula_1, u_1 = fit_gaussian_copula(X_1)

# Generar muestras nuevas
def generate_copula_samples(copula, num_samples, preprocessor):
    synth_u = copula.rvs(nobs=num_samples)
    synth_x = norm.ppf(synth_u)

    num_pipe = preprocessor.named_transformers_['num']
    cat_pipe = preprocessor.named_transformers_['cat']

    n_num = len(num_pipe.named_steps['scaler'].mean_)

    synth_num_scaled = synth_x[:, :n_num]
    synth_cat_encoded = synth_x[:, n_num:]

    # Manually inverse only the scaler (skip imputer)
    scaler = num_pipe.named_steps['scaler']
    synth_num = scaler.inverse_transform(synth_num_scaled)

    # Categorical inverse
    ohe = cat_pipe.named_steps['onehot']
    synth_cat = ohe.inverse_transform(synth_cat_encoded)

    synth_array = np.column_stack([synth_num, synth_cat])
    
    original_columns = num_cols + cat_cols
    return pd.DataFrame(synth_array, columns=original_columns)

In [50]:
# generar 100 por clase
synth_0 = generate_copula_samples(copula_0, 1000, preprocessor)
synth_1 = generate_copula_samples(copula_1, 1000, preprocessor)

# convertir a dataframe y agregar el targer
df_synth_0 = pd.DataFrame(synth_0, columns=df_0.columns)
df_synth_0[target_col] = 0
df_synth_1 = pd.DataFrame(synth_1, columns=df_1.columns)
df_synth_1[target_col] = 1

# data augmentado
df_aug = pd.concat([df, df_synth_0, df_synth_1], ignore_index=True)
df_aug.head()

,duracion_s,rms_mean,rms_std,dementia,dementia type,gender,ethnicity,f0_mean,f0_std,f0_range,...,propn_ratio,noun_pron_ratio,syntax_depth,std_words_per_sent,mean_word_length,std_word_length,function_ratio,duration,pause_prob,wpm
0,71.019688,0.07139,0.050389,1,Alzheimer,male,Caucasian/White,174.444418,51.103025,311.05542,...,0.037975,0.465517,7.666667,75.330383,3.78903,2.132184,0.611814,72.76,0.263634,195.437053
1,47.0,0.144582,0.090372,1,Dementia,female,Black/African American,292.169978,115.242586,659.783615,...,0.0,0.5,5.5,13.379088,3.810811,1.850315,0.628378,47.04,0.122493,188.77551
2,38.0,0.12396,0.079574,1,Dementia,female,Black/African American,238.856939,58.060892,352.463261,...,0.0,0.655172,5.428571,12.290697,3.625,1.952562,0.585938,38.4,0.000328,200.0
3,90.0,0.061281,0.049997,1,Dementia,female,Black/African American,255.297147,68.547493,638.292396,...,0.0,1.146341,5.357143,9.598044,4.003597,2.092292,0.57554,89.0,0.002673,187.41573
4,55.0,0.06031,0.051383,1,Dementia,male,Caucasian/White,134.696479,38.961565,243.928633,...,0.067073,1.0,4.5,8.890444,4.286585,2.216252,0.640244,55.0,0.149834,178.909091

In [51]:
d_bayes = validate_augmented_data(df, df_aug)
d_bayes

Validación de datos médicos

Estadísticas por variable:
duracion_s: Original=56.02, Sintético=55.47, diff=1.0%
rms_mean: Original=0.09, Sintético=0.09, diff=0.8%
rms_std: Original=0.06, Sintético=0.06, diff=1.2%
dementia: Original=0.37, Sintético=0.48, diff=29.5%
f0_mean: Original=178.47, Sintético=175.78, diff=1.5%
f0_std: Original=48.84, Sintético=46.38, diff=5.1%
f0_range: Original=300.61, Sintético=295.10, diff=1.8%
articulation_rate: Original=1.85, Sintético=1.86, diff=0.7%
silence_segments_n: Original=54.00, Sintético=53.50, diff=0.9%
silence_dur_mean_s: Original=0.28, Sintético=0.28, diff=1.1%

Distribuciones categóricas:

dementia type
 Lewy body: original=5.0%, sintético=0.5%
 Parkinson: original=1.4%, sintético=0.1%
 Alzheimer: original=27.5%, sintético=2.7%
 Dementia: original=24.3%, sintético=2.4%
 no dementia: original=40.8%, sintético=94.2%
 Primary progressive aphasia: original=0.9%, sintético=0.1%

gender
 male: original=85.6%, sintético=53.9%
 female: original=14.4%, sintético=46.1%

ethnicity
 Caucasian/White: original=83.3%, sintético=41.5%
 Hispanic: original=0.5%, sintético=23.7%
 Asian: original=0.5%, sintético=0.0%
 Black/African American: original=13.9%, sintético=34.6%
 Indian Subcontinent: original=1.9%, sintético=0.2%

dementia
 0: original=62.9%, sintético=51.9%
 1: original=37.1%, sintético=48.1%

Correlaciones principales:
dementia_f0_mean: Original=0.025, Sintético=0.003, diff=2.19%
dementia_articulation_rate: Original=-0.015, Sintético=0.010, diff=2.44%
dementia_HNRdBACF_sma3nz_amean: Original=0.049, Sintético=0.018, diff=3.10%

,type,variable,category,original,synthetic,diff_pct
0,numeric_mean,duracion_s,NaN,56.019615,55.466443,0.987460
1,numeric_mean,rms_mean,NaN,0.089943,0.090683,0.822961
2,numeric_mean,rms_std,NaN,0.061699,0.062422,1.170599
3,numeric_mean,dementia,NaN,0.371105,0.480663,29.522163
4,numeric_mean,f0_mean,NaN,178.469345,175.780553,1.506585
5,numeric_mean,f0_std,NaN,48.843398,46.375183,5.053324
6,numeric_mean,f0_range,NaN,300.610748,295.101545,1.832670
7,numeric_mean,articulation_rate,NaN,1.847707,1.859954,0.662846
8,numeric_mean,silence_segments_n,NaN,53.997167,53.496180,0.927802
9,numeric_mean,silence_dur_mean_s,NaN,0.281062,0.277861,1.139167
10,categorical,dementia type,Lewy body,5.045872,0.495942,4.549929
11,categorical,dementia type,Parkinson,1.376147,0.135257,1.240890
12,categorical,dementia type,Alzheimer,27.522936,2.705140,24.817796
13,categorical,dementia type,Dementia,24.311927,2.389540,21.922386
14,categorical,dementia type,no dementia,40.825688,94.183950,53.358261
15,categorical,dementia type,Primary progressive aphasia,0.917431,0.090171,0.827260
16,categorical,gender,male,85.648148,53.880866,31.767282
17,categorical,gender,female,14.351852,46.119134,31.767282
18,categorical,ethnicity,Caucasian/White,83.333333,41.516245,41.817088
19,categorical,ethnicity,Hispanic,0.462963,23.691336,23.228373
20,categorical,ethnicity,Asian,0.462963,0.045126,0.417837
21,categorical,ethnicity,Black/African American,13.888889,34.566787,20.677898
22,categorical,ethnicity,Indian Subcontinent,1.851852,0.180505,1.671346
23,categorical,dementia,0,62.889518,51.933702,10.955817
24,categorical,dementia,1,37.110482,48.066298,10.955817
25,correlation,dementia_f0_mean,NaN,0.024626,0.002683,2.194325
26,correlation,dementia_articulation_rate,NaN,-0.014581,0.009810,2.439058
27,correlation,dementia_HNRdBACF_sma3nz_amean,NaN,0.049397,0.018347,3.104991

In [41]:
df_aug.shape

(2353, 74)

In [42]:
# guardar el dataset
df_aug.to_csv('data_aumentada_copulas.csv')

## Redes neuronales

In [7]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [8]:
# identifica columnas
num_cols = [col for col in df.columns if df[col].dtype in ['float64', 'int64'] and col != 'dementia']
cat_cols = ['dementia type', 'gender', 'ethnicity']
target_col = 'dementia'

In [13]:
# preprocesing: imputacion y encoding

num_transformer = Pipeline(steps=[
  ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
    
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_transformer, num_cols),
        ('cat', cat_transformer, cat_cols)
    ]
)

X = preprocessor.fit_transform(df.drop(columns=[target_col]))
y = df[target_col].values


# Dataset para PyTorch

dataset = TensorDataset(torch.tensor(X, dtype=torch.float32), torch.tensor(y, dtype=torch.long))
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

# dimesion de input
input_dim = X.shape[1]
latent_dim = 20
num_classes = 2

# modelo VAE condicionado en clase
class ConditionalVAE(nn.Module):
    def __init__(self, input_dim, latent_dim, num_classes):
        super(ConditionalVAE, self).__init__()
        # encoder
        self.encoder = nn.Sequential(
            nn.Linear(input_dim + num_classes, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU()
        )
        self.mu = nn.Linear(64, latent_dim)
        self.logvar = nn.Linear(64, latent_dim)
        # decoder
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim + num_classes, 64),
            nn.ReLU(),
            nn.Linear(64, 128),
            nn.ReLU(),
            nn.Linear(128, input_dim)
        )
    def encode(self, x, c):
        h = self.encoder(torch.cat([x, c], dim=1))
        return self.mu(h), self.logvar(h)

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z, c):
        return self.decoder(torch.cat([z, c], dim=1))

    def forward(self, x, c):
        mu, logvar = self.encode(x, c)
        z = self.reparameterize(mu, logvar)
        return self.decode(z, c), mu, logvar

# funcion de perdida VAE
def vae_loss(recon_x, x, mu, logvar):
    recon_loss = nn.functional.mse_loss(recon_x, x, reduction='sum')
    kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
    return recon_loss + kl_loss

# entrenamiento
model = ConditionalVAE(input_dim, latent_dim, num_classes)
optimizer = optim.Adam(model.parameters(), lr=1e-3)

epochs = 100
for epoch in range(epochs):
    model.train()
    train_loss = 0
    for batch_x, batch_y in dataloader:
        c = torch.nn.functional.one_hot(batch_y, num_classes=num_classes).float()
        optimizer.zero_grad()
        recon_batch, mu, logvar = model(batch_x, c)
        loss = vae_loss(recon_batch, batch_x, mu, logvar)
        loss.backward()
        train_loss += loss.item()
        optimizer.step()
    print(f'Epoch {epoch+1}: Loss{train_loss/len(dataloader.dataset)}')

# generar datos augmentados
def generate_samples(model, num_samples, class_label):
    model.eval()
    with torch.no_grad():
        c = torch.nn.functional.one_hot(torch.full((num_samples,), class_label, dtype=torch.long), num_classes=num_classes).float()
        z = torch.randn(num_samples, latent_dim)
        samples = model.decode(z, c).numpy()
        return samples

# generar 100 por clase
synth_0 = generate_samples(model, 100, 0)
synth_1 = generate_samples(model, 100, 1)

Epoch 1: Loss73.2091282312323
Epoch 2: Loss71.94137089110636
Epoch 3: Loss71.1836689200685
Epoch 4: Loss70.50083003706027
Epoch 5: Loss68.78261735824282
Epoch 6: Loss64.13859244716741
Epoch 7: Loss61.44804299114109
Epoch 8: Loss60.24197004064284
Epoch 9: Loss58.495187732383144
Epoch 10: Loss56.84163224865965
Epoch 11: Loss54.94286852180114
Epoch 12: Loss53.22358193546111
Epoch 13: Loss51.66634267315311
Epoch 14: Loss50.256942630151855
Epoch 15: Loss49.5349654124749
Epoch 16: Loss48.725341461873256
Epoch 17: Loss48.330713169432904
Epoch 18: Loss47.248199484503644
Epoch 19: Loss46.724582931475325
Epoch 20: Loss46.40869064979445
Epoch 21: Loss45.852225338771056
Epoch 22: Loss44.61967308325403
Epoch 23: Loss44.631407448657846
Epoch 24: Loss43.964752164846104
Epoch 25: Loss43.63428000215093
Epoch 26: Loss43.532262710268704
Epoch 27: Loss42.947394849220686
Epoch 28: Loss42.633895528215184
Epoch 29: Loss42.38079064561017
Epoch 30: Loss42.28830161378336
Epoch 31: Loss42.165855537392936
Epoch 32: Loss41.296595235721924
Epoch 33: Loss41.44806169720614
Epoch 34: Loss41.08283502724623
Epoch 35: Loss40.83441421465563
Epoch 36: Loss40.83382988516399
Epoch 37: Loss40.6897611320863
Epoch 38: Loss40.4045265349045
Epoch 39: Loss40.49364977180114
Epoch 40: Loss39.69023232824742
Epoch 41: Loss39.99342632563864
Epoch 42: Loss39.39880974096887
Epoch 43: Loss39.06426760427675
Epoch 44: Loss38.92881973742088
Epoch 45: Loss39.01077550396366
Epoch 46: Loss38.671263524560686
Epoch 47: Loss38.48774712754376
Epoch 48: Loss38.11444163119827
Epoch 49: Loss37.61203976596043
Epoch 50: Loss37.24736876663338
Epoch 51: Loss37.754597434241106
Epoch 52: Loss37.48899675969024
Epoch 53: Loss37.393252278184754
Epoch 54: Loss37.547679793057966
Epoch 55: Loss37.235956402743504
Epoch 56: Loss36.815820483242824
Epoch 57: Loss36.468788157779166
Epoch 58: Loss36.456576879571585
Epoch 59: Loss36.57106002937295
Epoch 60: Loss36.13091046816904
Epoch 61: Loss35.948066949168954
Epoch 62: Loss35.88909984512978
Epoch 63: Loss35.09917876808231
Epoch 64: Loss35.48365326576125
Epoch 65: Loss35.14131808618648
Epoch 66: Loss35.489112119161376
Epoch 67: Loss35.583198925591056
Epoch 68: Loss35.50402607255887
Epoch 69: Loss35.23714563191444
Epoch 70: Loss34.710123510603864
Epoch 71: Loss34.91762432498229
Epoch 72: Loss34.90334098534949
Epoch 73: Loss34.73696459048868
Epoch 74: Loss34.232888035328465
Epoch 75: Loss34.101922389130415
Epoch 76: Loss33.94214516658621
Epoch 77: Loss34.203735664951225
Epoch 78: Loss34.401609091177875
Epoch 79: Loss34.200128852476816
Epoch 80: Loss34.226952377189654
Epoch 81: Loss33.99083645418075
Epoch 82: Loss33.951113249695
Epoch 83: Loss33.36655897189132
Epoch 84: Loss33.41877251103647
Epoch 85: Loss33.20833728131086
Epoch 86: Loss32.7037278356363
Epoch 87: Loss33.221777156797415
Epoch 88: Loss33.15668994374045
Epoch 89: Loss33.08623756430305
Epoch 90: Loss32.68668067759225
Epoch 91: Loss32.69938747200682
Epoch 92: Loss32.67801693816361
Epoch 93: Loss32.54238901867745
Epoch 94: Loss32.47189166255443
Epoch 95: Loss32.56651584960246
Epoch 96: Loss32.546626250399406
Epoch 97: Loss32.36598539487498
Epoch 98: Loss32.23862483211009
Epoch 99: Loss31.96311389825837
Epoch 100: Loss32.308294831186785

In [15]:
#df_synth = pd.concat([synth_0, synth_1], ignore_index=True)
#df_augmentado = pd.concat([df, df_synth], ignore_index=True)